services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always

  pgadmin:
    container_name: dev-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  celery_worker:
    build: .
    command: celery -A backend.app.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres

  celery_beat:
    build: .
    command: celery -A backend.app.celery beat --loglevel=info
    depends_on:
      - redis
      - celery_worker
