services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: my_database
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always

